### ISSUE TITLE
All authorizations were not finalized by the CA

### ISSUE THREAD

**Issue by jbedo** [polhenarejos/acme_email#29]
Trying to use the automatic IMAP authenticator but keep encounting the above error. The tail of the log contains this:

```
 {"status": "pending", "expires": "2022-03-08T21:22:53.040Z", "identifier": {"type": "dns", "value": "cu@cua0.org"}, "challenges": [{"url": "https://acme.castle.cloud/acme/chall/Ix9vQfZmAoX", "type": "email-reply-00", "token": "-zONmIiLI5FrRYv1_XE69A", "status": "processing", "from": "acme+Nv8k2CHaVOt@castle.cloud"}]}                    
 2022-03-08 08:24:52,866:DEBUG:acme.client:Storing nonce: xJARMomWfdJlVfn64M9cdw 
 2022-03-08 08:24:52,867:DEBUG:certbot._internal.error_handler:Encountered exception:
 Traceback (most recent call last):                                              
   File "/nix/store/x4p8la6frp2nbxl8207dvh0w2cngl8gg-python3.9-certbot-1.22.0/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 105, in handle_authorizations
     self._poll_authorizations(authzrs, max_retries, best_effort)                
   File "/nix/store/x4p8la6frp2nbxl8207dvh0w2cngl8gg-python3.9-certbot-1.22.0/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 209, in _poll_authorizations
     raise errors.AuthorizationError('All authorizations were not finalized by the CA.')
 certbot.errors.AuthorizationError: All authorizations were not finalized by the CA.
 ```
 
 I've tried a few times, any suggestions?

**Comment by polhenarejos** [comment]
Could you try again?

**Comment by jbedo** [comment]
Worked perfectly, thanks!
