### ISSUE TITLE
Erorrs "All authorizations were not finalized by the CA" followed by response 500 errors

### ISSUE THREAD

**Issue by jbedo** [polhenarejos/acme_email#34]
I encounted the first error when trying to create a certificate:

```
2023-06-30 11:15:21,205:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/nix/store/qifkbxi0s3v0b7bi6yg9pblljlqfc4qg-python3.9-certbot-1.22.0/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 105, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/nix/store/qifkbxi0s3v0b7bi6yg9pblljlqfc4qg-python3.9-certbot-1.22.0/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 209, in _poll_authorizations
    raise errors.AuthorizationError('All authorizations were not finalized by the CA.')
certbot.errors.AuthorizationError: All authorizations were not finalized by the CA.
```

I though i'd try again and specify just a digial signature with `--usage digitalSignature` but now i'm getting 500 errors:

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -                
The ACME response has been sent successfully!                                                  
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -                
An unexpected error occurred:                                                                  
acme.errors.ClientError: <Response [500]>     
```

Happy to attach logs if it helps, just not sure which bits of it need redacting.

**Comment by polhenarejos** [comment]
First error is due to email provider, which does not notifies the server for new mails for the first time. It usually takes a second attempt to work smoothly.

Error 500 was fixed at server side, so `--usage digitalSignature` is accepted again.

Thanks for the warning.
