### ISSUE TITLE
All authorizations were not finalized by the CA.

### ISSUE THREAD

**Issue by Cameo007** [polhenarejos/acme_email#36]
I see `ERROR:certbot._internal.log:All authorizations were not finalized by the CA.`.

I am running the following command for an Outlook email address:
`sudo python3 cli.py cert --config-dir . --work-dir . --logs-dir . --contact me@hotmail.com -e me@hotmail.com`

**Comment by polhenarejos** [comment]
Is it still happening?

**Comment by Cameo007** [comment]
Idk. But I'll test it.

**Comment by W7RZL** [comment]
I'm seeing this too. I couldn't get the automatic IMAP/SMTP method to work, so I tried the interactive method. Got the initial email, replied with the response and got "All authorizations were not finalized by the CA."

```
2024-01-12 10:06:14,978:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "cli.py", line 265, in <module>
    main(args)
  File "cli.py", line 203, in main
    request_cert(args, config)
  File "cli.py", line 125, in request_cert
    cert_path, chain_path, fullchain_path = certbot_main._csr_get_and_save_cert(config, le_client)
  File "/home/kmills/git/acme_email/venv/lib/python3.8/site-packages/certbot/_internal/main.py", line 1516, in _csr_get_and_save_cert
    cert, chain = le_client.obtain_certificate_from_csr(csr)
  File "/home/kmills/git/acme_email/venv/lib/python3.8/site-packages/certbot/_internal/client.py", line 334, in obtain_certificate_from_csr
    orderr = self._get_order_and_authorizations(csr.data, best_effort=False)
  File "/home/kmills/git/acme_email/venv/lib/python3.8/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/home/kmills/git/acme_email/venv/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/home/kmills/git/acme_email/venv/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 216, in _poll_authorizations
    raise errors.AuthorizationError('All authorizations were not finalized by the CA.')
certbot.errors.AuthorizationError: All authorizations were not finalized by the CA.
2024-01-12 10:06:14,980:ERROR:certbot._internal.log:All authorizations were not finalized by the CA.
```

**Comment by polhenarejos** [comment]
Our mail provider sometimes throttles us. Try in few minutes.
