### ISSUE TITLE
All authorizations were not finalized by the CA

### ISSUE THREAD

**Issue by realpixelcode** [polhenarejos/acme_email#39]
Over the last few days, I repeatedly tried getting a certificate (with a break of a few to 30 minutes between all attempts) using the command

```
python3 cli.py cert --config-dir . --work-dir . --logs-dir . -e pixelcode@dismail.de --contact smime@example.org --imap --login pixelcode@dismail.de --password "xxx" --host imap.dismail.de --ssl --smtp-method STARTTLS --smtp-port 587 --smtp-host smtp.dismail.de --passphrase "xxx" --usage digitalSignature --usage keyEncipherment
```

but only ever received this error:

```
{"status": "pending", "expires": "2024-02-11T18:51:07.797Z", "identifier": {"type": "dns", "value": "pixelcode@dismail.de"}, "challenges": [{"url": "https://acme.castle.cloud/acme/chall/xxx", "type": "email-reply-00", "token": "xxx", "status": "processing", "from": "acme+xxx@castle.cloud"}]}
2024-02-10 19:53:44,153:DEBUG:acme.client:Storing nonce: xxx
2024-02-10 19:53:44,154:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/home/pixelcode/Applications/acme_email/venv/lib/python3.10/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/home/pixelcode/Applications/acme_email/venv/lib/python3.10/site-packages/certbot/_internal/auth_handler.py", line 216, in _poll_authorizations
    raise errors.AuthorizationError('All authorizations were not finalized by the CA.')
certbot.errors.AuthorizationError: All authorizations were not finalized by the CA.

2024-02-10 19:53:44,155:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-02-10 19:53:44,155:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-02-10 19:53:44,155:DEBUG:imapclient.imapclient:< DONE
2024-02-10 19:53:44,155:DEBUG:imapclient.imaplib:< b'* 255 EXISTS'
2024-02-10 19:53:44,155:DEBUG:imapclient.imaplib:	matched b'\\* (?P<data>\\d+) (?P<type>[A-Z-]+)( (?P<data2>.*))?' => (b'255', b'EXISTS', None, None)
2024-02-10 19:53:44,155:DEBUG:imapclient.imaplib:untagged_responses[EXISTS] 1 += ["b'255'"]
2024-02-10 19:53:44,155:DEBUG:imapclient.imaplib:< b'* 1 RECENT'
2024-02-10 19:53:44,156:DEBUG:imapclient.imaplib:	matched b'\\* (?P<data>\\d+) (?P<type>[A-Z-]+)( (?P<data2>.*))?' => (b'1', b'RECENT', None, None)
2024-02-10 19:53:44,156:DEBUG:imapclient.imaplib:untagged_responses[RECENT] 1 += ["b'1'"]
2024-02-10 20:09:56,268:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/home/pixelcode/Applications/acme_email/cli.py", line 265, in <module>
    main(args)
  File "/home/pixelcode/Applications/acme_email/cli.py", line 203, in main
    request_cert(args, config)
  File "/home/pixelcode/Applications/acme_email/cli.py", line 125, in request_cert
    cert_path, chain_path, fullchain_path = certbot_main._csr_get_and_save_cert(config, le_client)
  File "/home/pixelcode/Applications/acme_email/venv/lib/python3.10/site-packages/certbot/_internal/main.py", line 1516, in _csr_get_and_save_cert
    cert, chain = le_client.obtain_certificate_from_csr(csr)
  File "/home/pixelcode/Applications/acme_email/venv/lib/python3.10/site-packages/certbot/_internal/client.py", line 334, in obtain_certificate_from_csr
    orderr = self._get_order_and_authorizations(csr.data, best_effort=False)
  File "/home/pixelcode/Applications/acme_email/venv/lib/python3.10/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/home/pixelcode/Applications/acme_email/venv/lib/python3.10/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/home/pixelcode/Applications/acme_email/venv/lib/python3.10/site-packages/certbot/_internal/auth_handler.py", line 216, in _poll_authorizations
    raise errors.AuthorizationError('All authorizations were not finalized by the CA.')
certbot.errors.AuthorizationError: All authorizations were not finalized by the CA.
2024-02-10 20:09:56,269:ERROR:certbot._internal.log:All authorizations were not finalized by the CA.
```

**Comment by elenium3** [comment]
Same. It's a pity

**Comment by polhenarejos** [comment]
I changed the backend for another.

Try again and reopen if persists.

**Comment by realpixelcode** [comment]
Thanks, it worked fine today! 🥳
