### ISSUE TITLE
'Namespace' object has no attribute 'renewal_pre_hooks_dir'

### ISSUE THREAD

**Issue by jamacoe** [polhenarejos/acme_email#43]
When trying to run this, I always receive error 
**'Namespace' object has no attribute 'renewal_pre_hooks_dir'**:

[1006 Mon Sep 23 14:09:07 root@.local /home/me/acme_email/acme_email-0.14.1]$ 
**python3 cli.py cert --config-dir . --work-dir . --logs-dir . --contact me@myotherdomain.es -e me@mydomain.es --imap --login me@mydomain.es --password "<mypassword>" --host imap.myimaphost.com --ssl --smtp-method SSL --smtp-port 465 --smtp-host mail.mysmtphost.com  --agree-tos** 

Saving debug log to ./letsencrypt.log

An unexpected error occurred:

AttributeError: **'Namespace' object has no attribute 'renewal_pre_hooks_dir'**

Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile ./letsencrypt.log or re-run Certbot with -v for more details.

[1005 Mon Sep 23 14:07:56 root@.local /home/me/acme_email/acme_email-0.14.1]$ **cat ./letsencrypt.log**

2024-09-23 14:07:56,162:DEBUG:certbot._internal.log:Root logging level set at 30
2024-09-23 14:07:56,163:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "cli.py", line 264, in <module>
    main(args)
  File "cli.py", line 195, in main
    certbot_main.make_or_verify_needed_dirs(config)
  File "/usr/local/lib/python3.6/site-packages/certbot/_internal/main.py", line 1583, in make_or_verify_needed_dirs
    hook_dirs = (config.renewal_pre_hooks_dir,
AttributeError: 'Namespace' object has no attribute 'renewal_pre_hooks_dir'
2024-09-23 14:07:56,163:ERROR:certbot._internal.log:An unexpected error occurred:
2024-09-23 14:07:56,163:ERROR:certbot._internal.log:AttributeError: 'Namespace' object has no attribute 'renewal_pre_hooks_dir'

**Comment by polhenarejos** [comment]
Version of certbot?

**Comment by jamacoe** [comment]
$ snap list certbot
Name     Version  Rev   Tracking       Publisher     Notes
certbot  2.4.0    2836  latest/stable  certbot-eff✓  classic

**Comment by polhenarejos** [comment]
Can you update to a more recent version? v2.4 is too old.
